### ISSUE TITLE
Question: What is the difference between WatchedMutationLink and withClientState (Apollo)

### ISSUE THREAD

**Issue by MHerszak** [haytko/apollo-link-watched-mutation#1]
WatchedMutationLink seems very similar to withClientState and I was wondering if withClientState resulted from WatchedMutionLink? withClientState is never mentioned in the Apollo talk.

**Comment by c316** [comment]
These do look very similar

https://github.com/apollographql/apollo-link-state

**Comment by haytko** [comment]
Hey, sorry about the late reply on this:

As far as I can tell, apollo-link-state and apollo-link-watched-mutation have similar APIs but quite distinct goals. I'm not too experienced with apollo-link-state so please correct me if I'm wrong.

apollo-link-state aims to provides a way for you to store and interact with client-side data. To do that, it accepts a cache reference and some resolvers for interacting with the cache.

apollo-link-watched-mutation has one aim and that aim is to make updating the cache after mutations easier. To do that, it accepts a cache reference and a map of explicit relationships between queries and mutations. 

So, in my example here: https://github.com/haytko/apollo-link-watched-mutation/blob/master/README.md#example-usage we're passing in a map that says in english:

"For every successful SaveTodo mutation that comes back, invoke this provided callback for every cached TodoListQuery mutation. If the callback provides something new, write that value to the cache"

So, withClientState empowers your app to store whatever you want in apollo's cache but my watchedMutationLink provides a new way to update the cache after a mutation.

Does that help clear up the difference at all ?

**Comment by MHerszak** [comment]
@haytko you actually answered the question in the Apollo Slack channel, on the day I asked it. So no late reply on your side :) Thanks for clarifying it for me, anyway!
