### ISSUE TITLE
Callback triggered twice after refetch

### ISSUE THREAD

**Issue by miguelocarvajal** [haytko/apollo-link-watched-mutation#13]
I am having an issue where the callback defined in WatchedMutationLink gets called twice (or more) if a related query is refetched.

Looking through the code I see that addRelatedQuery is called every time the query is fetched with no control over "duplicates".

Is this the expected behavior?

**Comment by haytko** [comment]
Hey Miguel, thanks for opening this issue. You're absolutely right that this was an issue and I just published a 0.2.4 that should address this and added a refetch button to the example todo app to enable easy testing of this type of functionality.

**Comment by miguelocarvajal** [comment]
That was quick! Thanks!
