### ISSUE TITLE
Documentation | Query results can be read-only

### ISSUE THREAD

**Issue by lindlof** [haytko/apollo-link-watched-mutation#9]
I was sometimes getting errors when assigning new items to query result - the same way the example assigns `updatedResult.todos.items`.

It seems that this is an error we get later in the life-cycle of queries, not immediately after they are cached. Now I would be lying if I said I know Apollo and the Link interface like my pockets but it looks like links are supposed to handle data and return results in an immutable way. 

My suggestion is to update the example to handle data in immutable manner:
```
let updatedItems = null;
if (isTodoIncluded && !shouldTodoBeIncluded) {
  updatedItems = cachedTodos.filter(todo => todo.id !== mutatedTodoId);
} else if (!isTodoIncluded && shouldTodoBeIncluded) {
  updatedItems = [updatedTodo, ...cachedTodos];
}
if (updatedItems) {
  return {
    ...query.result,
    todos: {
      ...query.result.todos,
      items: updatedItems,
    },
  };
}
```

**Comment by haytko** [comment]
Hmm, interesting, I never ran into issues like that in my testing but this sounds very reasonable.

Would you like to submit a PR or shall I copy & paste ? Thanks for the feedback again 👍

**Comment by lindlof** [comment]
Not sure what exactly is causing these troubles for me and not for you. I'm generally having these issues with immutability. I think it's because I'm using AWS AppSync Link and it's not working perfectly together with Apollo client.

Anyhow doing immutable updates fixes things for me and seems like the correct way of updating items in any setup. I'll be back with a PR.

**Comment by haytko** [comment]
Closing thanks to PR: https://github.com/haytko/apollo-link-watched-mutation/pull/10
